name: John Vandivier
favicon: null
layout_spectrum: 0.23185358080081642
title: John Vandivier
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
typography_spectrum: 0.0691632789094001
